# Generated by Django 4.1.5 on 2023-01-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="img",
            field=models.ImageField(default="aaa", upload_to="gallery"),
            preserve_default=False,
        ),
    ]
